name: Build Android app

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Android debug build
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload artifacts - app.icampuspass_debug.apk
        uses: actions/upload-artifact@v4
        with:
          name: app.icampuspass_debug.apk
          path: ./androidApp/build/outputs/apk/debug/androidApp-debug.apk
          if-no-files-found: ignore
      - name: Upload artifacts - app.icampuspass_release_unsigned.apk
        uses: actions/upload-artifact@v4
        with:
          name: app.icampuspass_release_unsigned.apk
          path: ./androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk
          if-no-files-found: ignore
      - name: Upload artifacts - sdkDependencies_debug.txt
        uses: actions/upload-artifact@v4
        with:
          name: sdkDependencies_debug.txt
          path: ./androidApp/build/outputs/sdk-dependencies/debug/sdkDependencies.txt
          if-no-files-found: ignore
      - name: Upload artifacts - sdkDependencies_release.txt
        uses: actions/upload-artifact@v4
        with:
          name: sdkDependencies_release.txt
          path: ./androidApp/build/outputs/sdk-dependencies/release/sdkDependencies.txt
          if-no-files-found: ignore
