name: Lint Gradle

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Lint
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Gradle lint
        run: ./gradlew lint --stacktrace
      - name: Output lint-results-debug.txt
        run: if [ -f ./androidApp/build/reports/lint-results-debug.txt ] ; then cat ./androidApp/build/reports/lint-results-debug.txt ; fi
      - name: Upload artifacts - problems-report.html
        uses: actions/upload-artifact@v4
        with:
          name: problems-report.html
          path: ./build/reports/problems/problems-report.html
          if-no-files-found: ignore
      - name: Upload artifacts - lint-results-debug.html
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug.html
          path: ./androidApp/build/reports/lint-results-debug.html
          if-no-files-found: ignore
      - name: Upload artifacts - lint-results-debug.txt
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug.txt
          path: ./androidApp/build/reports/lint-results-debug.txt
          if-no-files-found: ignore
      - name: Upload artifacts - lint-results-debug.xml
        uses: actions/upload-artifact@v4
        with:
          name: lint-results-debug.xml
          path: ./androidApp/build/reports/lint-results-debug.xml
          if-no-files-found: ignore
